version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    ports:
      - 5000:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/warehouse
    depends_on:
      - db
  db:
    build:
      context: db
      dockerfile: Dockerfile
    expose:
      - 5432
